# Generated by Django 4.0.4 on 2022-06-13 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_check'),
    ]

    operations = [
        migrations.CreateModel(
            name='correction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checknumber', models.IntegerField()),
                ('checklist', models.CharField(max_length=200)),
            ],
        ),
    ]
