# Generated by Django 4.0.4 on 2022-06-15 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0006_alter_correction_checknumber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='correction',
            old_name='checknumber',
            new_name='hostname',
        ),
    ]
